(import spork/test :prefix "")
(import /env)

(start-suite "make-id")
(assert (deep= (string (env/make-id ["1"])) "1"))
(assert (= (string (env/make-id ["1a"])) "1a"))
(assert (= (string (env/make-id ["a1"])) "a1"))
(assert (= (string (env/make-id ["1 1"])) "1-1"))
(assert (= (string (env/make-id ["1    1"])) "1-1"))
(assert (= (string (env/make-id ["1.1"])) "11"))
(assert (= (string (env/make-id [" 1"])) "-1"))
(assert (= (string (env/make-id ["-1"])) "1"))
(assert (= (string (env/make-id [".1"])) "1"))
(assert (= (string (env/make-id ["$1"])) "1"))
(assert (= (string (env/make-id ["$a"])) "a"))
(assert (= (string (env/make-id ["11"])) "11"))
(assert (= (string (env/make-id ["aa"])) "aa"))
(assert (= (string (env/make-id ["a$"])) "a"))
(end-suite)

(start-suite "numeric-id")
(assert (= (string (env/numeric-id "1")) "1"))
(assert (= (string (env/numeric-id "1" "1")) "1.1"))
(assert (= (string (env/numeric-id "1" "2")) "1.2"))
(assert (= (string (env/numeric-id "1" "2" "3")) "1.2.3"))
(end-suite)

(start-suite "simple elements")
(assert (= (env/title "This is a title") [:h1 "This is a title"]))
(assert (= (env/comment "This is a title") ""))
(assert (= (env/comment (env/title "This is a commented title")) ""))
(end-suite)

(start-suite "anchor")
(assert (deep= (env/anchor ["anchor"]) [:a {:href "#anchor"} ["anchor"]]))
(assert (deep= (env/anchor ["anchor two"]) [:a {:href "#anchor-two"} ["anchor two"]]))
(assert (deep= (env/anchor @["anchor as array"]) [:a {:href "#anchor-as-array"} @["anchor as array"]]))
(end-suite)
